name: tjhoisington
favicon: null
layout_spectrum: 0.18713194271549582
typography_spectrum: 0.840699648950249
title: Bestselling Author and Motivational Speaker – TJ Hoisington
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8407867611385882
  lightness: 0.3961761579848826
  saturation: 0.06715620961040258
  rhythmicContrast: 0.894376888172701
purpose: []
